instance_provision: 'spot'
spot_max_price: 0.60
instance_provision_fallback_on_demand: false
region_name:
  - eu-west-1
user_credentials_path: '~/.ssh/scylla-qa-ec2'
instance_type_loader: 'c5.xlarge'
instance_type_monitor: 't3.large'
# manual on creating loader AMI's: see docs/new_loader_ami.md
regions_data:
  us-east-1: # US East (N. Virginia)
    ami_id_loader: 'ami-04ba971b593b243c5' # Loader dedicated AMI v18
    ami_id_monitor: 'ami-02eac2c0129f6376b' # Official CentOS Linux 7 x86_64 HVM EBS ENA 1901_01
  us-west-2: # US West (Oregon)
    ami_id_loader: 'ami-034e122f3d6577a73' # Loader dedicated AMI v18
    ami_id_monitor: 'ami-01ed306a12b7d1c96' # Official CentOS Linux 7 x86_64 HVM EBS ENA 1901_01
  eu-west-1: # Europe (Ireland)
    ami_id_loader: 'ami-0f2aac9a9d7a29979' # Loader dedicated AMI v18
    ami_id_monitor: 'ami-0ff760d16d9497662' # Official CentOS Linux 7 x86_64 HVM EBS ENA 1901_01
  eu-west-2: # Europe (London)
    ami_id_loader: 'ami-099a7a92db81b3500' # Loader dedicated AMI v18
    ami_id_monitor: 'ami-0eab3a90fc693af19' # Official CentOS Linux 7 x86_64 HVM EBS ENA 1901_01
  eu-north-1: # Europe (Stockholm)
    ami_id_loader: 'ami-0f1099eae729b80f1' # Loader dedicated AMI v18
    ami_id_monitor: 'ami-5ee66f20' # Official CentOS Linux 7 x86_64 HVM EBS ENA 1901_01
  eu-central-1: # Europe (Frankfurt)
    ami_id_loader: 'ami-0cc124517d1f5710e' # Loader dedicated AMI v18
    ami_id_monitor: 'ami-04cf43aca3e6f3de3' # Official CentOS Linux 7 x86_64 HVM EBS ENA 1901_01

root_disk_size_monitor: 50  # GB, remove this field if default disk size should be used
root_disk_size_db: 30  # GB, increase root disk for larger swap (maximum: 16G)
root_disk_size_loader: 30  # GB, Increase loader disk in order to have extra space for a larger swap
loader_swap_size: 10240  #10GB SWAP space
ami_db_scylla_user: 'scyllaadm'
# used prepared centos7 AMI for loader
ami_loader_user: 'centos'
# centos7 is used for monitor
ami_monitor_user: 'centos'
aws_instance_profile_name: 'qa-scylla-manager-backup-instance-profile'

ami_id_db_scylla: ''
ami_id_db_oracle: ''

use_preinstalled_scylla: true

backup_bucket_backend: 's3'
backup_bucket_location: 'manager-backup-tests-us-east-1'
backup_bucket_region: 'us-east-1'

data_volume_disk_num: 0
data_volume_disk_type: 'gp2'
data_volume_disk_size: 500
data_volume_disk_iops: 10000 # depend on type iops could be 100-16000 for io2|io3 and 3000-16000 for gp3
